name: kmerseek-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bitarray=3.0.0=py312h66e93f0_0
  - bitstring=4.3.0=pyhd8ed1ab_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.1.31=hbcca054_0
  - cachetools=5.5.1=pyhd8ed1ab_0
  - cffi=1.17.1=py312h06ac9bb_0
  - click=8.1.8=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.1=py312h68727a3_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - deprecation=2.1.0=pyh9f0ad1d_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - fonttools=4.55.8=py312h178313f_0
  - freetype=2.12.1=h267a509_2
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - kiwisolver=1.4.8=py312h84d6215_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=28_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=28_he106b2a_openblas
  - libdeflate=1.23=h4ddbbb0_0
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=28_h7ac8fdf_openblas
  - liblzma=5.6.4=hb9d3cd8_0
  - liblzma-devel=5.6.4=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libpng=1.6.46=h943b412_0
  - libsqlite=3.48.0=hee588c1_1
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.7.0=hd9ff511_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-base=3.10.0=py312hd3ec401_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=h2d0b736_3
  - numpy=2.2.2=py312h72c5963_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.4.0=h7b32b05_1
  - packaging=24.2=pyhd8ed1ab_2
  - pillow=11.1.0=py312h80c1187_0
  - pip=25.0=pyh8b19718_0
  - pluggy=1.5.0=pyhd8ed1ab_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyh29332c3_1
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pytest=8.3.4=pyhd8ed1ab_1
  - python=3.12.8=h9e4cc4f_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.12=5_cp312
  - qhull=2020.2=h434a139_5
  - readline=8.2=h8228510_1
  - scipy=1.15.1=py312h180e4f1_0
  - screed=1.1.3=pyhd8ed1ab_0
  - setuptools=75.8.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - sourmash=4.8.14=hdfd78af_0
  - sourmash-minimal=4.8.14=py312h3753b3a_1
  - sourmash_plugin_branchwater=0.9.13=py312hae1b4d1_1
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.2.1=pyhd8ed1ab_1
  - tzdata=2025a=h78e105d_0
  - unicodedata2=16.0.0=py312h66e93f0_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xz=5.6.4=hbcc6ac9_0
  - xz-gpl-tools=5.6.4=hbcc6ac9_0
  - xz-tools=5.6.4=hb9d3cd8_0
  - zstd=1.5.6=ha6fb4c9_0
prefix: /home/ec2-user/miniconda3/envs/kmerseek-dev
