name: kmerseek-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - bitarray
  - bitstring
  - brotli
  - brotli-bin
  - bzip2
  - ca-certificates
  - cachetools
  - cffi
  - click
  - colorama
  - contourpy
  - cycler
  - deprecation
  - exceptiongroup
  - fonttools
  - freetype
  - iniconfig
  - kiwisolver
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libdeflate
  - libexpat
  - libffi
  - libgcc
  - libgcc-ng
  - libgfortran
  - libgfortran5
  - libgomp
  - libjpeg-turbo
  - liblapack
  - liblzma
  - liblzma-devel
  - libnsl
  - libopenblas
  - libpng
  - libsqlite
  - libstdcxx
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp-base
  - libxcb
  - libxcrypt
  - libzlib
  - matplotlib-base
  - munkres
  - ncurses
  - numpy
  - openjpeg
  - openssl
  - packaging
  - pillow
  - pip
  - pluggy
  - pthread-stubs
  - pycparser
  - pyparsing
  - pytest
  - python
  - python-dateutil
  - python_abi
  - qhull
  - readline
  - scipy
  - screed
  - setuptools
  - six
  - sourmash
  - sourmash-minimal
  - sourmash_plugin_branchwater
  - tk
  - tomli
  - tzdata
  - unicodedata2
  - wheel
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - xz-gpl-tools
  - xz-tools
  - zstd
